### ISSUE TITLE
Updates to change First Published Date script

### ISSUE THREAD

**Issue by MarcLaf** [babakdanyal/SharePoint#1]
Hello,
I'm not sure how to make pull requests yet but just some updates for the script.
* The preferred method for connecting is now -Interactive and not -UseWebLogin
* -SystemUpdate:$true is obsolete and has been replaced with -UpdateType SystemUpdate

Thanks for the script too! This helps us modify the sort as we usually clone a previous item as a template for news posts.

**Comment by babakdanyal** [comment]
Thanks for the update @MarcLaf , I will update the script.

And I am not sure what's your use case but you can create multiple news template pages as per your organization and let the content-editors choose which one they want to use.

**Comment by MarcLaf** [comment]
I had no idea you could make templates! Will have to look into this,
thanks.
